spring:
  application:
    name: @project.name@
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:dotask}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  
  security:
    oauth2:
      resourceserver:
        jwt:
          audiences:
          - ${security.token.jwt.audience}
          public-key-location: ${security.token.jwt.public-key-path}

security:
  token:
    jwt:
      private-key-path: file:${JWT_PRIVATE_KEY_PATH}
      public-key-path: file:${JWT_PUBLIC_KEY_PATH}
      issuer: ${JWT_ISSUER}
      audience: ${JWT_AUDIENCE}
    access:
      lifespan: ${ACCESS_TOKEN_LIFESPAN:15m}
    refresh:
      lifespan: ${REFRESH_TOKEN_LIFESPAN:1d}
    email-verification:
      lifespan: ${EMAIL_VERIFICATION_TOKEN_LIFESPAN:1h}
    password-reset:
      lifespan: ${PASSWORD_RESET_TOKEN_LIFESPAN:1h}
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:*}
    allowed-methods: ${CORS_ALLOWED_METHODS:*}
    