spring:
  application:
    name: @project.name@
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:dotask}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  
  security:
    oauth2:
      resourceserver:
        jwt:
          audiences:
          - ${security.token.jwt.audience}
          public-key-location: ${security.token.jwt.public-key-path}

  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:25}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: ${MAIL_SMTP_AUTH:true}
          starttls:
            enable: ${MAIL_STARTTLS_ENABLE:true}
            required: ${MAIL_STARTTLS_REQUIRED:false}

logging:
  level:
    org.springframework.security: INFO

security:
  token:
    jwt:
      private-key-path: file:${JWT_PRIVATE_KEY_PATH:.keys/private.pem}
      public-key-path: file:${JWT_PUBLIC_KEY_PATH:.keys/public.pem}
      audience: ${JWT_AUDIENCE:dotask}
      issuer: ${JWT_ISSUER:dotask}
    access:
      lifespan: ${ACCESS_TOKEN_LIFESPAN:15m}
    refresh:
      lifespan: ${REFRESH_TOKEN_LIFESPAN:1d}
    email-verification:
      lifespan: ${EMAIL_VERIFICATION_TOKEN_LIFESPAN:1h}
    password-reset:
      lifespan: ${PASSWORD_RESET_TOKEN_LIFESPAN:1h}
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:*}
    allowed-methods: ${CORS_ALLOWED_METHODS:*}
    