CREATE TABLE IF NOT EXISTS revoked_tokens (
    jti UUID PRIMARY KEY NOT NULL,
    user_id UUID NOT NULL,
    revoked_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL
);